#*****************************************************************************************
# Vivado (TM) v2018.3 (64-bit)
#
# build.tcl: Tcl script for re-creating project 'project_1'
#
# Generated by Vivado on Tue Jul 09 09:41:00 -0300 2019
# IP Build 2404404 on Fri Dec  7 01:43:56 MST 2018
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (build.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    "C:/Users/mathe/Documents/embraRT/project_1/project_1.srcs/sources_1/ip/c_shift_ram_10/c_shift_ram_10.xci"
#    "C:/Users/mathe/Documents/embraRT/project_1/project_1.srcs/sources_1/ip/c_shift_ram_9/c_shift_ram_9.xci"
#    "C:/Users/mathe/Documents/embraRT/project_1/project_1.srcs/sources_1/ip/floating_point_2/floating_point_2.xci"
#    "C:/Users/mathe/Documents/embraRT/project_1/project_1.srcs/sources_1/ip/c_shift_ram_11/c_shift_ram_11.xci"
#    "C:/Users/mathe/Documents/embraRT/project_1/project_1.srcs/sources_1/ip/blk_mem_gen_5/blk_mem_gen_5.xci"
#    "C:/Users/mathe/Documents/embraRT/project_1/coe_files/vectorH.coe"
#    "C:/Users/mathe/Documents/embraRT/project_1/coe_files/vetorV.coe"
#    "C:/Users/mathe/Documents/embraRT/project_1/coe_files/coe2.coe"
#    "C:/Users/mathe/Documents/embraRT/project_1/coe_files/nodes.coe"
#    "C:/Users/mathe/Documents/embraRT/project_1/coe_files/COE_file.coe"
#    "C:/Users/mathe/Documents/embraRT/project_1/coe_files/vetorV2.coe"
#    "C:/Users/mathe/Documents/embraRT/project_1/coe_files/nodes2.coe"
#    "C:/Users/mathe/Documents/embraRT/project_1/coe_files/nodes3.coe"
#    "C:/Users/mathe/Documents/embraRT/project_1/coe_files/hist.coe"
#    "C:/Users/mathe/Documents/embraRT/project_1/coe_files/vetorV_teste1.coe"
#    "C:/Users/mathe/Documents/embraRT/project_1/coe_files/vectorH_teste1.coe"
#    "C:/Users/mathe/Documents/embraRT/project_1/coe_files/COE_file_teste1.coe"
#    "C:/Users/mathe/Documents/embraRT/project_1/coe_files/hist_teste1.coe"
#    "C:/Users/mathe/Documents/embraRT/project_1/coe_files/nodes_teste1.coe"
#    "C:/Users/mathe/Documents/embraRT/project_1/coe_files/I_ROM_teste1.coe"
#    "C:/Users/mathe/Documents/embraRT/project_1/coe_files/vetorV_teste2.coe"
#    "C:/Users/mathe/Documents/embraRT/project_1/coe_files/vectorH_teste2.coe"
#    "C:/Users/mathe/Documents/embraRT/project_1/coe_files/COE_file_teste2.coe"
#    "C:/Users/mathe/Documents/embraRT/project_1/coe_files/I_ROM_teste2.coe"
#    "C:/Users/mathe/Documents/embraRT/project_1/coe_files/nodes_teste2.coe"
#    "C:/Users/mathe/Documents/embraRT/project_1/coe_files/hist_teste2.coe"
#
# 3. The following remote source files that were added to the original project:-
#
#    "C:/Users/mathe/Documents/embraRT/realTime_2/realTime_2.srcs/sources_1/ip/c_shift_ram_8/c_shift_ram_8.xci"
#    "C:/Users/mathe/Documents/embraRT/realTime_2/realTime_2.srcs/sources_1/ip/c_shift_ram_7/c_shift_ram_7.xci"
#    "C:/Users/mathe/Documents/embraRT/realTime_2/realTime_2.srcs/sources_1/ip/c_shift_ram_6_1/c_shift_ram_6.xci"
#    "C:/Users/mathe/Documents/embraRT/realTime_2/realTime_2.srcs/sources_1/ip/c_shift_ram_5/c_shift_ram_5.xci"
#    "C:/Users/mathe/Documents/embraRT/realTime_2/realTime_2.srcs/sources_1/ip/c_shift_ram_3/c_shift_ram_3.xci"
#    "C:/Users/mathe/Documents/embraRT/realTime_2/realTime_2.srcs/sources_1/ip/c_shift_ram_2_1/c_shift_ram_2.xci"
#    "C:/Users/mathe/Documents/embraRT/realTime_2/realTime_2.srcs/sources_1/ip/blk_mem_gen_3/blk_mem_gen_3.xci"
#    "C:/Users/mathe/Documents/embraRT/realTime_2/realTime_2.srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2.xci"
#    "C:/Users/mathe/Documents/embraRT/realTime_2/realTime_2.srcs/sources_1/ip/floating_point_5/floating_point_5.xci"
#    "C:/Users/mathe/Documents/embraRT/realTime_2/realTime_2.srcs/sources_1/ip/floating_point_4/floating_point_4.xci"
#    "C:/Users/mathe/Documents/embraRT/realTime_2/realTime_2.srcs/sources_1/ip/floating_point_3/floating_point_3.xci"
#    "C:/Users/mathe/Documents/embraRT/realTime_2/realTime_2.srcs/sources_1/ip/floating_point_1_1/floating_point_1.xci"
#    "C:/Users/mathe/Documents/embraRT/realTime_2/realTime_2.srcs/sources_1/ip/floating_point_0_1/floating_point_0.xci"
#    "C:/Users/mathe/Documents/embraRT/realTime_2/realTime_2.srcs/sources_1/ip/c_shift_ram_4/c_shift_ram_4.xci"
#    "C:/Users/mathe/Documents/embraRT/realTime_2/realTime_2.srcs/sources_1/ip/c_shift_ram_1_1/c_shift_ram_1.xci"
#    "C:/Users/mathe/Documents/embraRT/realTime_2/realTime_2.srcs/sources_1/ip/c_shift_ram_0_1/c_shift_ram_0.xci"
#    "C:/Users/mathe/Documents/embraRT/realTime_2/realTime_2.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.xci"
#    "C:/Users/mathe/Documents/embraRT/realTime_2/realTime_2.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.xci"
#    "C:/Users/mathe/Documents/embraRT/realTime_2/realTime_2.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci"
#    "C:/Users/mathe/Documents/embraRT/realTime_2/realTime_2.srcs/sources_1/new/accum.vhd"
#    "C:/Users/mathe/Documents/embraRT/realTime_2/realTime_2.srcs/sources_1/new/mult.vhd"
#    "C:/Users/mathe/Documents/embraRT/realTime_2/realTime_2.srcs/sources_1/new/MAC.vhd"
#    "C:/Users/mathe/Documents/embraRT/realTime_2/realTime_2.srcs/sources_1/new/arbiter.vhd"
#    "C:/Users/mathe/Documents/embraRT/realTime_2/realTime_2.srcs/sources_1/new/arbiterHIST.vhd"
#    "C:/Users/mathe/Documents/embraRT/realTime_2/realTime_2.srcs/sources_1/new/demux.vhd"
#    "C:/Users/mathe/Documents/embraRT/realTime_2/realTime_2.srcs/sources_1/new/histvect.vhd"
#    "C:/Users/mathe/Documents/embraRT/realTime_2/realTime_2.srcs/sources_1/new/vetmat.vhd"
#    "C:/Users/mathe/Documents/embraRT/realTime_2/realTime_2.srcs/sources_1/new/main.vhd"
#    "C:/Users/mathe/Documents/embraRT/realTime_2/realTime_2.srcs/sources_1/imports/Desktop/COE_file.coe"
#    "C:/Users/mathe/Documents/embraRT/realTime_2/realTime_2.srcs/sources_1/imports/Desktop/vectorH.coe"
#    "C:/Users/mathe/Documents/embraRT/realTime_2/realTime_2.srcs/sources_1/imports/Desktop/I.coe"
#    "C:/Users/mathe/Documents/embraRT/realTime_2/realTime_2.srcs/sim_1/imports/xilinxsIPfloating/TT_behav.wcfg"
#    "C:/Users/mathe/Documents/embraRT/realTime_2/realTime_2.srcs/sim_1/imports/xilinxsIPfloating/TT_behav1.wcfg"
#    "C:/Users/mathe/Documents/embraRT/realTime_2/realTime_2.srcs/sim_1/imports/new/FOUR_BIT_tb.vhd"
#    "C:/Users/mathe/Documents/embraRT/teste1/teste1_results.wcfg"
#
#*****************************************************************************************

# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

# Set the project name
set _xil_proj_name_ "project_1"

# Use project name variable, if specified in the tcl shell
if { [info exists ::user_project_name] } {
  set _xil_proj_name_ $::user_project_name
}

variable script_file
set script_file "build.tcl"

# Help information for this script
proc print_help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--project_name <name>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--project_name <name>\] Create project with the specified name. Default"
  puts "                       name is the name of the project from where this"
  puts "                       script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < $::argc} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir"   { incr i; set origin_dir [lindex $::argv $i] }
      "--project_name" { incr i; set _xil_proj_name_ [lindex $::argv $i] }
      "--help"         { print_help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/"]"

# Create project
create_project ${_xil_proj_name_} ./${_xil_proj_name_} -part xc7vx485tffg1761-2

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Set project properties
set obj [current_project]
set_property -name "board_part" -value "xilinx.com:vc707:part0:1.4" -objects $obj
set_property -name "default_lib" -value "xil_defaultlib" -objects $obj
set_property -name "dsa.accelerator_binary_content" -value "bitstream" -objects $obj
set_property -name "dsa.accelerator_binary_format" -value "xclbin2" -objects $obj
set_property -name "dsa.board_id" -value "vc707" -objects $obj
set_property -name "dsa.description" -value "Vivado generated DSA" -objects $obj
set_property -name "dsa.dr_bd_base_address" -value "0" -objects $obj
set_property -name "dsa.emu_dir" -value "emu" -objects $obj
set_property -name "dsa.flash_interface_type" -value "bpix16" -objects $obj
set_property -name "dsa.flash_offset_address" -value "0" -objects $obj
set_property -name "dsa.flash_size" -value "1024" -objects $obj
set_property -name "dsa.host_architecture" -value "x86_64" -objects $obj
set_property -name "dsa.host_interface" -value "pcie" -objects $obj
set_property -name "dsa.num_compute_units" -value "60" -objects $obj
set_property -name "dsa.platform_state" -value "pre_synth" -objects $obj
set_property -name "dsa.vendor" -value "xilinx" -objects $obj
set_property -name "dsa.version" -value "0.0" -objects $obj
set_property -name "enable_vhdl_2008" -value "1" -objects $obj
set_property -name "ip_cache_permissions" -value "read write" -objects $obj
set_property -name "ip_output_repo" -value "$proj_dir/${_xil_proj_name_}.cache/ip" -objects $obj
set_property -name "mem.enable_memory_map_generation" -value "1" -objects $obj
set_property -name "sim.central_dir" -value "$proj_dir/${_xil_proj_name_}.ip_user_files" -objects $obj
set_property -name "sim.ip.auto_export_scripts" -value "1" -objects $obj
set_property -name "simulator_language" -value "VHDL" -objects $obj
set_property -name "target_language" -value "VHDL" -objects $obj
set_property -name "webtalk.activehdl_export_sim" -value "108" -objects $obj
set_property -name "webtalk.ies_export_sim" -value "108" -objects $obj
set_property -name "webtalk.modelsim_export_sim" -value "108" -objects $obj
set_property -name "webtalk.questa_export_sim" -value "108" -objects $obj
set_property -name "webtalk.riviera_export_sim" -value "108" -objects $obj
set_property -name "webtalk.vcs_export_sim" -value "108" -objects $obj
set_property -name "webtalk.xsim_export_sim" -value "109" -objects $obj
set_property -name "webtalk.xsim_launch_sim" -value "335" -objects $obj
set_property -name "xpm_libraries" -value "XPM_MEMORY" -objects $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/../realTime_2/realTime_2.srcs/sources_1/ip/c_shift_ram_8/c_shift_ram_8.xci"] \
 [file normalize "${origin_dir}/../realTime_2/realTime_2.srcs/sources_1/ip/c_shift_ram_7/c_shift_ram_7.xci"] \
 [file normalize "${origin_dir}/../realTime_2/realTime_2.srcs/sources_1/ip/c_shift_ram_6_1/c_shift_ram_6.xci"] \
 [file normalize "${origin_dir}/../realTime_2/realTime_2.srcs/sources_1/ip/c_shift_ram_5/c_shift_ram_5.xci"] \
 [file normalize "${origin_dir}/../realTime_2/realTime_2.srcs/sources_1/ip/c_shift_ram_3/c_shift_ram_3.xci"] \
 [file normalize "${origin_dir}/../realTime_2/realTime_2.srcs/sources_1/ip/c_shift_ram_2_1/c_shift_ram_2.xci"] \
 [file normalize "${origin_dir}/../realTime_2/realTime_2.srcs/sources_1/ip/blk_mem_gen_3/blk_mem_gen_3.xci"] \
 [file normalize "${origin_dir}/../realTime_2/realTime_2.srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2.xci"] \
 [file normalize "${origin_dir}/../realTime_2/realTime_2.srcs/sources_1/ip/floating_point_5/floating_point_5.xci"] \
 [file normalize "${origin_dir}/../realTime_2/realTime_2.srcs/sources_1/ip/floating_point_4/floating_point_4.xci"] \
 [file normalize "${origin_dir}/../realTime_2/realTime_2.srcs/sources_1/ip/floating_point_3/floating_point_3.xci"] \
 [file normalize "${origin_dir}/../realTime_2/realTime_2.srcs/sources_1/ip/floating_point_1_1/floating_point_1.xci"] \
 [file normalize "${origin_dir}/../realTime_2/realTime_2.srcs/sources_1/ip/floating_point_0_1/floating_point_0.xci"] \
 [file normalize "${origin_dir}/../realTime_2/realTime_2.srcs/sources_1/ip/c_shift_ram_4/c_shift_ram_4.xci"] \
 [file normalize "${origin_dir}/../realTime_2/realTime_2.srcs/sources_1/ip/c_shift_ram_1_1/c_shift_ram_1.xci"] \
 [file normalize "${origin_dir}/../realTime_2/realTime_2.srcs/sources_1/ip/c_shift_ram_0_1/c_shift_ram_0.xci"] \
 [file normalize "${origin_dir}/../realTime_2/realTime_2.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.xci"] \
 [file normalize "${origin_dir}/../realTime_2/realTime_2.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.xci"] \
 [file normalize "${origin_dir}/../realTime_2/realTime_2.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci"] \
 [file normalize "${origin_dir}/../realTime_2/realTime_2.srcs/sources_1/new/accum.vhd"] \
 [file normalize "${origin_dir}/../realTime_2/realTime_2.srcs/sources_1/new/mult.vhd"] \
 [file normalize "${origin_dir}/../realTime_2/realTime_2.srcs/sources_1/new/MAC.vhd"] \
 [file normalize "${origin_dir}/../realTime_2/realTime_2.srcs/sources_1/new/arbiter.vhd"] \
 [file normalize "${origin_dir}/../realTime_2/realTime_2.srcs/sources_1/new/arbiterHIST.vhd"] \
 [file normalize "${origin_dir}/../realTime_2/realTime_2.srcs/sources_1/new/demux.vhd"] \
 [file normalize "${origin_dir}/../realTime_2/realTime_2.srcs/sources_1/new/histvect.vhd"] \
 [file normalize "${origin_dir}/../realTime_2/realTime_2.srcs/sources_1/new/vetmat.vhd"] \
 [file normalize "${origin_dir}/../realTime_2/realTime_2.srcs/sources_1/new/main.vhd"] \
 [file normalize "${origin_dir}/../realTime_2/realTime_2.srcs/sources_1/imports/Desktop/COE_file.coe"] \
 [file normalize "${origin_dir}/../realTime_2/realTime_2.srcs/sources_1/imports/Desktop/vectorH.coe"] \
 [file normalize "${origin_dir}/../realTime_2/realTime_2.srcs/sources_1/imports/Desktop/I.coe"] \
 [file normalize "${origin_dir}/../realTime_2/realTime_2.srcs/sim_1/imports/xilinxsIPfloating/TT_behav.wcfg"] \
 [file normalize "${origin_dir}/../realTime_2/realTime_2.srcs/sim_1/imports/xilinxsIPfloating/TT_behav1.wcfg"] \
]
add_files -norecurse -fileset $obj $files

# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/project_1.srcs/sources_1/ip/c_shift_ram_10/c_shift_ram_10.xci" ]\
 [file normalize "${origin_dir}/project_1.srcs/sources_1/ip/c_shift_ram_9/c_shift_ram_9.xci" ]\
 [file normalize "${origin_dir}/project_1.srcs/sources_1/ip/floating_point_2/floating_point_2.xci" ]\
 [file normalize "${origin_dir}/project_1.srcs/sources_1/ip/c_shift_ram_11/c_shift_ram_11.xci" ]\
 [file normalize "${origin_dir}/project_1.srcs/sources_1/ip/blk_mem_gen_5/blk_mem_gen_5.xci" ]\
 [file normalize "${origin_dir}/coe_files/vectorH.coe" ]\
 [file normalize "${origin_dir}/coe_files/vetorV.coe" ]\
 [file normalize "${origin_dir}/coe_files/coe2.coe" ]\
 [file normalize "${origin_dir}/coe_files/nodes.coe" ]\
 [file normalize "${origin_dir}/coe_files/COE_file.coe" ]\
 [file normalize "${origin_dir}/coe_files/vetorV2.coe" ]\
 [file normalize "${origin_dir}/coe_files/nodes2.coe" ]\
 [file normalize "${origin_dir}/coe_files/nodes3.coe" ]\
 [file normalize "${origin_dir}/coe_files/hist.coe" ]\
 [file normalize "${origin_dir}/coe_files/vetorV_teste1.coe" ]\
 [file normalize "${origin_dir}/coe_files/vectorH_teste1.coe" ]\
 [file normalize "${origin_dir}/coe_files/COE_file_teste1.coe" ]\
 [file normalize "${origin_dir}/coe_files/hist_teste1.coe" ]\
 [file normalize "${origin_dir}/coe_files/nodes_teste1.coe" ]\
 [file normalize "${origin_dir}/coe_files/I_ROM_teste1.coe" ]\
 [file normalize "${origin_dir}/coe_files/vetorV_teste2.coe" ]\
 [file normalize "${origin_dir}/coe_files/vectorH_teste2.coe" ]\
 [file normalize "${origin_dir}/coe_files/COE_file_teste2.coe" ]\
 [file normalize "${origin_dir}/coe_files/I_ROM_teste2.coe" ]\
 [file normalize "${origin_dir}/coe_files/nodes_teste2.coe" ]\
 [file normalize "${origin_dir}/coe_files/hist_teste2.coe" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/../realTime_2/realTime_2.srcs/sources_1/ip/c_shift_ram_8/c_shift_ram_8.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "$origin_dir/../realTime_2/realTime_2.srcs/sources_1/ip/c_shift_ram_7/c_shift_ram_7.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "$origin_dir/../realTime_2/realTime_2.srcs/sources_1/ip/c_shift_ram_6_1/c_shift_ram_6.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "$origin_dir/../realTime_2/realTime_2.srcs/sources_1/ip/c_shift_ram_5/c_shift_ram_5.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "$origin_dir/../realTime_2/realTime_2.srcs/sources_1/ip/c_shift_ram_3/c_shift_ram_3.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "$origin_dir/../realTime_2/realTime_2.srcs/sources_1/ip/c_shift_ram_2_1/c_shift_ram_2.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "$origin_dir/../realTime_2/realTime_2.srcs/sources_1/ip/blk_mem_gen_3/blk_mem_gen_3.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "$origin_dir/../realTime_2/realTime_2.srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "$origin_dir/../realTime_2/realTime_2.srcs/sources_1/ip/floating_point_5/floating_point_5.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "$origin_dir/../realTime_2/realTime_2.srcs/sources_1/ip/floating_point_4/floating_point_4.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "$origin_dir/../realTime_2/realTime_2.srcs/sources_1/ip/floating_point_3/floating_point_3.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "$origin_dir/../realTime_2/realTime_2.srcs/sources_1/ip/floating_point_1_1/floating_point_1.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "$origin_dir/../realTime_2/realTime_2.srcs/sources_1/ip/floating_point_0_1/floating_point_0.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "$origin_dir/../realTime_2/realTime_2.srcs/sources_1/ip/c_shift_ram_4/c_shift_ram_4.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "$origin_dir/../realTime_2/realTime_2.srcs/sources_1/ip/c_shift_ram_1_1/c_shift_ram_1.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "$origin_dir/../realTime_2/realTime_2.srcs/sources_1/ip/c_shift_ram_0_1/c_shift_ram_0.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "$origin_dir/../realTime_2/realTime_2.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "$origin_dir/../realTime_2/realTime_2.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "$origin_dir/../realTime_2/realTime_2.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "$origin_dir/../realTime_2/realTime_2.srcs/sources_1/new/accum.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../realTime_2/realTime_2.srcs/sources_1/new/mult.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../realTime_2/realTime_2.srcs/sources_1/new/MAC.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../realTime_2/realTime_2.srcs/sources_1/new/arbiter.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../realTime_2/realTime_2.srcs/sources_1/new/arbiterHIST.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../realTime_2/realTime_2.srcs/sources_1/new/demux.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../realTime_2/realTime_2.srcs/sources_1/new/histvect.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../realTime_2/realTime_2.srcs/sources_1/new/vetmat.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/../realTime_2/realTime_2.srcs/sources_1/new/main.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj


# Set 'sources_1' fileset file properties for local files
set file "c_shift_ram_10/c_shift_ram_10.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "c_shift_ram_9/c_shift_ram_9.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "floating_point_2/floating_point_2.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "c_shift_ram_11/c_shift_ram_11.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "blk_mem_gen_5/blk_mem_gen_5.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property -name "top" -value "main" -objects $obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Empty (no sources present)

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
set files [list \
 [file normalize "${origin_dir}/../realTime_2/realTime_2.srcs/sim_1/imports/new/FOUR_BIT_tb.vhd"] \
 [file normalize "${origin_dir}/../teste1/teste1_results.wcfg"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sim_1' fileset file properties for remote files
set file "$origin_dir/../realTime_2/realTime_2.srcs/sim_1/imports/new/FOUR_BIT_tb.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj


# Set 'sim_1' fileset file properties for local files
# None

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property -name "sim_mode" -value "post-implementation" -objects $obj
set_property -name "top" -value "TT" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj
set_property -name "top_lib" -value "xil_defaultlib" -objects $obj

# Set 'utils_1' fileset object
set obj [get_filesets utils_1]
# Empty (no sources present)

# Set 'utils_1' fileset properties
set obj [get_filesets utils_1]

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
    create_run -name synth_1 -part xc7vx485tffg1761-2 -flow {Vivado Synthesis 2018} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2018" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Synthesis Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'synth_1_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0] "" ] } {
  create_report_config -report_name synth_1_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs synth_1
}
set obj [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0]
if { $obj != "" } {
set_property -name "display_name" -value "synth_1_synth_report_utilization_0" -objects $obj

}
set obj [get_runs synth_1]
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
    create_run -name impl_1 -part xc7vx485tffg1761-2 -flow {Vivado Implementation 2018} -strategy "Vivado Implementation Defaults" -report_strategy {No Reports} -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2018" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Implementation Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'impl_1_init_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_init_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps init_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "display_name" -value "impl_1_init_report_timing_summary_0" -objects $obj

}
# Create 'impl_1_opt_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_drc_0 -report_type report_drc:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0]
if { $obj != "" } {
set_property -name "display_name" -value "impl_1_opt_report_drc_0" -objects $obj

}
# Create 'impl_1_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "display_name" -value "impl_1_opt_report_timing_summary_0" -objects $obj

}
# Create 'impl_1_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "display_name" -value "impl_1_power_opt_report_timing_summary_0" -objects $obj

}
# Create 'impl_1_place_report_io_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0] "" ] } {
  create_report_config -report_name impl_1_place_report_io_0 -report_type report_io:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0]
if { $obj != "" } {
set_property -name "display_name" -value "impl_1_place_report_io_0" -objects $obj

}
# Create 'impl_1_place_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0] "" ] } {
  create_report_config -report_name impl_1_place_report_utilization_0 -report_type report_utilization:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0]
if { $obj != "" } {
set_property -name "display_name" -value "impl_1_place_report_utilization_0" -objects $obj

}
# Create 'impl_1_place_report_control_sets_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0] "" ] } {
  create_report_config -report_name impl_1_place_report_control_sets_0 -report_type report_control_sets:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0]
if { $obj != "" } {
set_property -name "display_name" -value "impl_1_place_report_control_sets_0" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "display_name" -value "impl_1_place_report_incremental_reuse_0" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_1' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_1 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "display_name" -value "impl_1_place_report_incremental_reuse_1" -objects $obj

}
# Create 'impl_1_place_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_place_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "display_name" -value "impl_1_place_report_timing_summary_0" -objects $obj

}
# Create 'impl_1_post_place_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_place_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_place_power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "display_name" -value "impl_1_post_place_power_opt_report_timing_summary_0" -objects $obj

}
# Create 'impl_1_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "display_name" -value "impl_1_phys_opt_report_timing_summary_0" -objects $obj

}
# Create 'impl_1_route_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_route_report_drc_0 -report_type report_drc:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0]
if { $obj != "" } {
set_property -name "display_name" -value "impl_1_route_report_drc_0" -objects $obj

}
# Create 'impl_1_route_report_methodology_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0] "" ] } {
  create_report_config -report_name impl_1_route_report_methodology_0 -report_type report_methodology:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0]
if { $obj != "" } {
set_property -name "display_name" -value "impl_1_route_report_methodology_0" -objects $obj

}
# Create 'impl_1_route_report_power_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0] "" ] } {
  create_report_config -report_name impl_1_route_report_power_0 -report_type report_power:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0]
if { $obj != "" } {
set_property -name "display_name" -value "impl_1_route_report_power_0" -objects $obj

}
# Create 'impl_1_route_report_route_status_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0] "" ] } {
  create_report_config -report_name impl_1_route_report_route_status_0 -report_type report_route_status:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0]
if { $obj != "" } {
set_property -name "display_name" -value "impl_1_route_report_route_status_0" -objects $obj

}
# Create 'impl_1_route_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_route_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0]
if { $obj != "" } {
set_property -name "display_name" -value "impl_1_route_report_timing_summary_0" -objects $obj

}
# Create 'impl_1_route_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_route_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0]
if { $obj != "" } {
set_property -name "display_name" -value "impl_1_route_report_incremental_reuse_0" -objects $obj

}
# Create 'impl_1_route_report_clock_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0] "" ] } {
  create_report_config -report_name impl_1_route_report_clock_utilization_0 -report_type report_clock_utilization:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0]
if { $obj != "" } {
set_property -name "display_name" -value "impl_1_route_report_clock_utilization_0" -objects $obj

}
# Create 'impl_1_route_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_route_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0]
if { $obj != "" } {
set_property -name "display_name" -value "impl_1_route_report_bus_skew_0" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "display_name" -value "impl_1_post_route_phys_opt_report_timing_summary_0" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0]
if { $obj != "" } {
set_property -name "display_name" -value "impl_1_post_route_phys_opt_report_bus_skew_0" -objects $obj

}
set obj [get_runs impl_1]
set_property -name "strategy" -value "Vivado Implementation Defaults" -objects $obj
set_property -name "steps.write_bitstream.args.readback_file" -value "0" -objects $obj
set_property -name "steps.write_bitstream.args.verbose" -value "0" -objects $obj

# set the current impl run
current_run -implementation [get_runs impl_1]

puts "INFO: Project created:${_xil_proj_name_}"
set obj [get_dashboards default_dashboard]

# Create 'drc_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets -of_objects [get_dashboards default_dashboard] [ list "drc_1" ] ] ""]} {
create_dashboard_gadget -name {drc_1} -type drc
}
set obj [get_dashboard_gadgets -of_objects [get_dashboards default_dashboard] [ list "drc_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_drc_0" -objects $obj

# Create 'methodology_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets -of_objects [get_dashboards default_dashboard] [ list "methodology_1" ] ] ""]} {
create_dashboard_gadget -name {methodology_1} -type methodology
}
set obj [get_dashboard_gadgets -of_objects [get_dashboards default_dashboard] [ list "methodology_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_methodology_0" -objects $obj

# Create 'power_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets -of_objects [get_dashboards default_dashboard] [ list "power_1" ] ] ""]} {
create_dashboard_gadget -name {power_1} -type power
}
set obj [get_dashboard_gadgets -of_objects [get_dashboards default_dashboard] [ list "power_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_power_0" -objects $obj

# Create 'timing_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets -of_objects [get_dashboards default_dashboard] [ list "timing_1" ] ] ""]} {
create_dashboard_gadget -name {timing_1} -type timing
}
set obj [get_dashboard_gadgets -of_objects [get_dashboards default_dashboard] [ list "timing_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_timing_summary_0" -objects $obj

# Create 'utilization_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets -of_objects [get_dashboards default_dashboard] [ list "utilization_1" ] ] ""]} {
create_dashboard_gadget -name {utilization_1} -type utilization
}
set obj [get_dashboard_gadgets -of_objects [get_dashboards default_dashboard] [ list "utilization_1" ] ]
set_property -name "reports" -value "synth_1#synth_1_synth_report_utilization_0" -objects $obj
set_property -name "run.step" -value "synth_design" -objects $obj
set_property -name "run.type" -value "synthesis" -objects $obj

# Create 'utilization_2' gadget (if not found)
if {[string equal [get_dashboard_gadgets -of_objects [get_dashboards default_dashboard] [ list "utilization_2" ] ] ""]} {
create_dashboard_gadget -name {utilization_2} -type utilization
}
set obj [get_dashboard_gadgets -of_objects [get_dashboards default_dashboard] [ list "utilization_2" ] ]
set_property -name "reports" -value "impl_1#impl_1_place_report_utilization_0" -objects $obj

move_dashboard_gadget -name {utilization_1} -row 0 -col 0
move_dashboard_gadget -name {power_1} -row 1 -col 0
move_dashboard_gadget -name {drc_1} -row 2 -col 0
move_dashboard_gadget -name {timing_1} -row 0 -col 1
move_dashboard_gadget -name {utilization_2} -row 1 -col 1
move_dashboard_gadget -name {methodology_1} -row 2 -col 1
# Set current dashboard to 'default_dashboard' 
current_dashboard default_dashboard 
